import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Agent worktrees — generated, not source
    ".claude/worktrees/**",
    // AOC package build output — generated by `npm run build:aoc`, not hand-written source.
    // The corresponding .ts source files are linted above; linting generated .d.ts/.js
    // output serves no purpose and produces spurious no-explicit-any errors.
    "src/aoc/*/dist/**",
  ]),
]);

export default eslintConfig;
