import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Agent worktrees — generated, not source
    ".claude/worktrees/**",
    // AOC package build output — generated by `npm run build:aoc`, not hand-written source.
    // The corresponding .ts source files are linted above; linting generated .d.ts/.js
    // output serves no purpose and produces spurious no-explicit-any errors.
    "src/aoc/*/dist/**",
    // Supabase CLI local-stack scratch — generated by `supabase start`, git-ignored
    // (supabase/.gitignore), never hand-written. Same rationale as the dist output above.
    // Left unignored it was the ONLY source of error-level findings in the repository: one
    // generated Deno edge-runtime file produced all 154, so `npm run lint` — and therefore
    // the BLOCKING Lint gate inside `check:beta-release` — failed for anyone with the
    // disposable local stack running, while passing in CI where the directory does not
    // exist. A release gate whose verdict depends on whether Docker happens to be up is
    // not a gate.
    "supabase/.temp/**",
  ]),
]);

export default eslintConfig;
