import { canonicalRaidFingerprint } from "../raid/extraction";
import type { RaidCategory } from "../raid/types";
import type { DecisionStatus, DecisionType } from "../decision-governance/types";
import type { BillingBlocker, ClosureBillingAssessment, ClosureBlocker } from "./closure-billing-types";

/**
 * Everything needed to create a real `RaidItem` (`src/lib/raid/types.ts`) from a closure/billing
 * blocker, except fields only a persistence layer can assign. Reuses `canonicalRaidFingerprint`
 * (RAID module) exactly like `operational-intelligence-mappers.ts` (Sprint 5) does — no parallel
 * RAID model. Pure data — never inserts a row, never persists anything.
 */
export type ClosureBillingRaidItemMappingInput = {
  workspaceId: string;
  projectId: string;
  category: RaidCategory;
  title: string;
  description: string;
  status: "open";
  owner: string | null;
  dueDate: string | null;
  autoGenerated: true;
  fingerprint: string;
};

/**
 * Everything needed to create a real `DecisionRecord` (`src/lib/decision-governance/types.ts`)
 * from a closure/billing blocker, except fields only a human/persistence layer can assign.
 * `recommendation_id` is nullable — unlike Sprint 5's operational drafts, a closure/billing
 * blocker does not necessarily originate from a `PlaybookRecommendation`, and this mapper never
 * fabricates one to fill the slot; it mirrors the real `DecisionRecord.recommendation_id`
 * nullability instead. `decision_status` is always `"draft"`.
 */
export type ClosureBillingDecisionRecordMappingInput = {
  workspace_id: string;
  project_id: string;
  decision_type: DecisionType;
  decision_status: Extract<DecisionStatus, "draft">;
  title: string;
  summary: string;
  decision_rationale: string | null;
  recommendation_id: string | null;
  metadata: Record<string, unknown>;
};

const CLOSURE_RAID_CATEGORY: Partial<Record<ClosureBlocker["type"], RaidCategory>> = {
  unresolved_risk: "risk",
  unresolved_issue: "issue",
  unresolved_dependency: "dependency",
};

const BILLING_RAID_CATEGORY: Partial<Record<BillingBlocker["type"], RaidCategory>> = {
  unresolved_issue: "issue",
  unresolved_dependency: "dependency",
};

function blockerToRaidInput(
  blocker: ClosureBlocker | BillingBlocker,
  category: RaidCategory | undefined,
  context: { workspaceId: string; projectId: string },
): ClosureBillingRaidItemMappingInput | null {
  if (!category) return null;
  return {
    workspaceId: context.workspaceId,
    projectId: context.projectId,
    category,
    title: blocker.description,
    description: blocker.suggestedAction,
    status: "open",
    owner: blocker.owner,
    dueDate: blocker.dueDate,
    autoGenerated: true,
    fingerprint: canonicalRaidFingerprint(category, `${blocker.type} ${blocker.description}`),
  };
}

/**
 * Maps a `ClosureBlocker` classified as risk/issue/dependency to a RAID mapping input. Returns
 * `null` for every other closure blocker type — those are governance/administrative concerns
 * RAID has no category for (see `closureBlockerToDecisionInput` for the governance path
 * instead). The caller decides if/when to actually call `persistRaidItems`.
 */
export function closureBlockerToOperationalDraftInput(
  blocker: ClosureBlocker,
  context: { workspaceId: string; projectId: string },
): ClosureBillingRaidItemMappingInput | null {
  return blockerToRaidInput(blocker, CLOSURE_RAID_CATEGORY[blocker.type], context);
}

/**
 * Maps a `BillingBlocker` classified as issue/dependency to a RAID mapping input. Returns `null`
 * for administrative/commercial blocker types (missing PO, missing report, etc.) — those are
 * surfaced through `nextBestActions`/communication templates instead of RAID objects.
 */
export function billingBlockerToOperationalDraftInput(
  blocker: BillingBlocker,
  context: { workspaceId: string; projectId: string },
): ClosureBillingRaidItemMappingInput | null {
  return blockerToRaidInput(blocker, BILLING_RAID_CATEGORY[blocker.type], context);
}

function decisionTypeForClosureBlocker(type: ClosureBlocker["type"]): DecisionType {
  if (type === "unknown_closure_rule") return "governance_exception";
  if (type === "missing_decision") return "other";
  return "other";
}

function decisionTypeForBillingBlocker(type: BillingBlocker["type"]): DecisionType {
  if (type === "unknown_billing_rule") return "governance_exception";
  return "other";
}

/**
 * Maps a `ClosureBlocker` that represents an unresolved rule/decision gap (`unknown_closure_rule`,
 * `missing_decision`) to a decision-governance mapping input. Returns `null` for every other
 * closure blocker type. Never persists; the caller decides if/when to actually create a
 * `DecisionRecord` through the decision-governance service.
 */
export function closureBlockerToDecisionInput(
  blocker: ClosureBlocker,
  context: { workspaceId: string; projectId: string },
): ClosureBillingDecisionRecordMappingInput | null {
  if (blocker.type !== "unknown_closure_rule" && blocker.type !== "missing_decision") return null;
  return {
    workspace_id: context.workspaceId,
    project_id: context.projectId,
    decision_type: decisionTypeForClosureBlocker(blocker.type),
    decision_status: "draft",
    title: blocker.description,
    summary: blocker.suggestedAction,
    decision_rationale: blocker.suggestedAction,
    recommendation_id: blocker.relatedRecommendationId,
    metadata: { closureBillingBlockerId: blocker.id, closureBillingBlockerType: blocker.type },
  };
}

/**
 * Maps a `BillingBlocker` representing an unknown/unvalidated billing rule to a decision-
 * governance mapping input. Returns `null` for every other billing blocker type. Never persists.
 */
export function billingBlockerToDecisionInput(
  blocker: BillingBlocker,
  context: { workspaceId: string; projectId: string },
): ClosureBillingDecisionRecordMappingInput | null {
  if (blocker.type !== "unknown_billing_rule") return null;
  return {
    workspace_id: context.workspaceId,
    project_id: context.projectId,
    decision_type: decisionTypeForBillingBlocker(blocker.type),
    decision_status: "draft",
    title: blocker.description,
    summary: blocker.suggestedAction,
    decision_rationale: blocker.suggestedAction,
    recommendation_id: blocker.relatedRecommendationId,
    metadata: { closureBillingBlockerId: blocker.id, closureBillingBlockerType: blocker.type },
  };
}

export type ClosureBillingCommunicationDraftInput = {
  projectId: string;
  workspaceId: string;
  templateId: NonNullable<ClosureBillingAssessment["recommendedCommunicationTemplateId"]>;
  reason: string;
  evidenceUsed: string[];
  missingEvidence: string[];
};

/**
 * Maps an assessment's `recommendedCommunicationTemplateId` to the input shape the
 * Communications Playbook (Sprint 4) would need to actually generate a draft (a real draft
 * still requires a `PlaybookRecommendation`/`CommunicationProjectContext`, which this module
 * intentionally does not fabricate). Returns `null` when no template is recommended. Never
 * generates or sends a communication draft itself.
 */
export function closureBillingAssessmentToCommunicationDraftInput(assessment: ClosureBillingAssessment): ClosureBillingCommunicationDraftInput | null {
  if (!assessment.recommendedCommunicationTemplateId) return null;
  return {
    projectId: assessment.projectId,
    workspaceId: assessment.workspaceId,
    templateId: assessment.recommendedCommunicationTemplateId,
    reason: assessment.explanation.nextBestAction ?? assessment.explanation.narrative,
    evidenceUsed: assessment.explanation.evidenceUsed,
    missingEvidence: assessment.explanation.missingEvidence,
  };
}
