import { canonicalRaidFingerprint } from "../raid/extraction";
import type { RaidCategory } from "../raid/types";
import type { DecisionStatus, DecisionType } from "../decision-governance/types";
import type { OperationalDraft } from "./operational-intelligence-types";

/**
 * Everything needed to create a real `RaidItem` (see `src/lib/raid/types.ts`), except the fields
 * only a persistence layer can assign (id, sourceDocumentId, detectedBy, timestamps,
 * occurrenceCount). Reuses `canonicalRaidFingerprint` (Sprint-independent RAID module) so a
 * converted draft naturally dedupes against RAID items already extracted from documents. Pure
 * data — mapping never inserts a row, never writes to any database, never runs on its own.
 */
export type RaidItemMappingInput = {
  workspaceId: string;
  projectId: string;
  category: RaidCategory;
  title: string;
  description: string;
  status: "open";
  owner: string | null;
  dueDate: string | null;
  autoGenerated: true;
  fingerprint: string;
};

/**
 * Everything needed to create a real `DecisionRecord` (see
 * `src/lib/decision-governance/types.ts`), except fields only a human/persistence layer can
 * assign (id, created_by, timestamps). `decision_status` is always `"draft"` — conversion into
 * `pending_review`/`approved` remains a decision-governance concern, never decided here. Pure
 * data — mapping never inserts a row, never persists anything.
 */
export type DecisionRecordMappingInput = {
  workspace_id: string;
  project_id: string;
  decision_type: DecisionType;
  decision_status: Extract<DecisionStatus, "draft">;
  title: string;
  summary: string;
  decision_rationale: string | null;
  recommendation_id: string;
  metadata: Record<string, unknown>;
};

const RAID_CATEGORY_BY_DRAFT_TYPE: Partial<Record<OperationalDraft["type"], RaidCategory>> = {
  risk: "risk",
  issue: "issue",
  dependency: "dependency",
};

/**
 * Maps a risk/issue/dependency `OperationalDraft` to the input shape the existing RAID module
 * (`src/lib/raid`) expects. Returns `null` for decision drafts — RAID has no "decision" category,
 * intentionally, so decisions are never forced into it (see `operationalDraftToDecisionInput`
 * instead). Never persists; the caller decides if/when to actually call `persistRaidItems`.
 */
export function operationalDraftToRaidItemInput(draft: OperationalDraft): RaidItemMappingInput | null {
  const category = RAID_CATEGORY_BY_DRAFT_TYPE[draft.type];
  if (!category) return null;

  return {
    workspaceId: draft.workspaceId,
    projectId: draft.projectId,
    category,
    title: draft.title,
    description: draft.description,
    status: "open",
    owner: draft.owner,
    dueDate: draft.dueDate,
    autoGenerated: true,
    fingerprint: canonicalRaidFingerprint(category, `${draft.title} ${draft.description}`),
  };
}

function decisionTypeForDraft(draft: OperationalDraft): DecisionType {
  if (draft.type === "risk" && (draft.category === "contractual" || draft.category === "commercial")) return "scope_change";
  if (draft.type === "risk") return "risk_response";
  if (draft.type === "dependency") return "dependency_resolution";
  return "other";
}

/**
 * Maps a `DecisionDraft` (or a risk/dependency draft that surfaced a decision alongside it) to
 * the input shape `src/lib/decision-governance` expects. Returns `null` for issue drafts — an
 * issue is never itself a decision. Never persists; the caller decides if/when to actually
 * create a `DecisionRecord` through the decision-governance service.
 */
export function operationalDraftToDecisionInput(draft: OperationalDraft): DecisionRecordMappingInput | null {
  if (draft.type === "issue") return null;

  return {
    workspace_id: draft.workspaceId,
    project_id: draft.projectId,
    decision_type: decisionTypeForDraft(draft),
    decision_status: "draft",
    title: draft.title,
    summary: draft.description,
    decision_rationale: draft.explanation.classifiedAsBecause,
    recommendation_id: draft.linkedRecommendationId,
    metadata: { operationalDraftFingerprint: draft.fingerprint, operationalDraftType: draft.type },
  };
}
