import type { DeliveryPlaybook } from "./types";

/**
 * The seed operational playbook: a generic, opinionated delivery methodology used
 * as the "brain" the Rules Engine and Recommendation Engine operate within.
 * This is static seed content for the MVP — the editable Playbook Registry
 * (multiple methodologies, per-workspace customization) is out of scope.
 */
export const SEED_DELIVERY_PLAYBOOK: DeliveryPlaybook = {
  id: "seed-delivery-playbook-v1",
  name: "Playbook de Entrega Estándar PMFreak",
  version: 1,
  description:
    "Metodología de delivery genérica cubriendo Iniciación, Planificación, Ejecución, Monitoreo & Control y Cierre. " +
    "Sirve como base gobernada sobre la que operan el Rules Engine y el Recommendation Engine.",
  phases: [
    {
      key: "iniciacion",
      name: "Iniciación",
      description: "Formalización del proyecto: charter, constitución y mapeo de stakeholders.",
      entryEvidence: [],
      exitEvidence: ["hasApprovedCharter", "hasApprovedConstitution", "hasStakeholderMap"],
    },
    {
      key: "planificacion",
      name: "Planificación",
      description: "Líneas base de alcance, cronograma y presupuesto; planes de riesgo y comunicaciones.",
      entryEvidence: ["hasApprovedCharter", "hasApprovedConstitution"],
      exitEvidence: [
        "hasScopeBaseline",
        "hasWbs",
        "hasScheduleBaseline",
        "hasBudgetBaseline",
        "hasRiskRegister",
        "hasCommunicationsPlan",
      ],
    },
    {
      key: "ejecucion",
      name: "Ejecución",
      description: "Entrega del trabajo planificado bajo control de alcance, cronograma y presupuesto.",
      entryEvidence: ["hasScopeBaseline", "hasScheduleBaseline", "hasBudgetBaseline"],
      exitEvidence: [],
    },
    {
      key: "monitoreo_control",
      name: "Monitoreo & Control",
      description: "Seguimiento continuo de riesgos, issues y desempeño en paralelo a la Ejecución.",
      entryEvidence: ["hasRiskRegister"],
      exitEvidence: [],
    },
    {
      key: "cierre",
      name: "Cierre",
      description: "Aceptación formal, cierre de facturación y lecciones aprendidas.",
      entryEvidence: [],
      exitEvidence: ["hasClientSignoff", "hasFinalInvoiceIssued", "hasClosureChecklistStarted"],
    },
  ],
  rules: [
    {
      id: "pb-init-charter-missing",
      scope: "iniciacion",
      title: "Charter del proyecto no aprobado",
      description: "El proyecto está en Iniciación pero no cuenta con un charter aprobado formalmente.",
      severity: "high",
      conditions: [{ fact: "hasApprovedCharter", operator: "is_false" }],
      evidenceFacts: ["hasApprovedCharter"],
      recommendationTemplate:
        "Priorizar la aprobación formal del charter del proyecto antes de avanzar a Planificación.",
    },
    {
      id: "pb-init-constitution-missing",
      scope: "iniciacion",
      title: "Constitución de proyecto no generada",
      description: "No existe una Constitución de Proyecto aprobada para gobernar decisiones futuras.",
      severity: "critical",
      conditions: [{ fact: "hasApprovedConstitution", operator: "is_false" }],
      evidenceFacts: ["hasApprovedConstitution"],
      recommendationTemplate:
        "Generar y someter a aprobación la Constitución del Proyecto antes de iniciar la planificación detallada.",
    },
    {
      id: "pb-init-stakeholder-map-missing",
      scope: "iniciacion",
      title: "Mapa de stakeholders ausente",
      description: "No se ha registrado un mapa de stakeholders (interés/influencia).",
      severity: "medium",
      conditions: [{ fact: "hasStakeholderMap", operator: "is_false" }],
      evidenceFacts: ["hasStakeholderMap"],
      recommendationTemplate: "Elaborar el mapa de stakeholders antes de cerrar la fase de Iniciación.",
    },
    {
      id: "pb-plan-scope-baseline-missing",
      scope: "planificacion",
      title: "Línea base de alcance no definida",
      description: "El proyecto está en Planificación sin una línea base de alcance aprobada.",
      severity: "high",
      conditions: [{ fact: "hasScopeBaseline", operator: "is_false" }],
      evidenceFacts: ["hasScopeBaseline"],
      recommendationTemplate: "Definir y aprobar la línea base de alcance antes de iniciar la Ejecución.",
    },
    {
      id: "pb-plan-wbs-missing",
      scope: "planificacion",
      title: "EDT/WBS no elaborada",
      description: "No existe una Estructura de Desglose del Trabajo derivada del alcance aprobado.",
      severity: "medium",
      conditions: [{ fact: "hasWbs", operator: "is_false" }],
      evidenceFacts: ["hasWbs"],
      recommendationTemplate: "Construir la EDT a partir de la línea base de alcance aprobada.",
    },
    {
      id: "pb-plan-schedule-baseline-missing",
      scope: "planificacion",
      title: "Línea base de cronograma no establecida",
      description: "No existe una línea base de cronograma formalmente aprobada.",
      severity: "high",
      conditions: [{ fact: "hasScheduleBaseline", operator: "is_false" }],
      evidenceFacts: ["hasScheduleBaseline"],
      recommendationTemplate: "Establecer la línea base de cronograma antes de aprobar el paso a Ejecución.",
    },
    {
      id: "pb-plan-budget-baseline-missing",
      scope: "planificacion",
      title: "Línea base de presupuesto no establecida",
      description: "No existe una línea base de presupuesto ni mecanismo de control de costos definido.",
      severity: "high",
      conditions: [{ fact: "hasBudgetBaseline", operator: "is_false" }],
      evidenceFacts: ["hasBudgetBaseline"],
      recommendationTemplate: "Establecer la línea base de presupuesto y su mecanismo de control de costos.",
    },
    {
      id: "pb-plan-comms-plan-missing",
      scope: "planificacion",
      title: "Plan de comunicaciones ausente",
      description: "No existe un Plan de Comunicaciones documentado para el proyecto.",
      severity: "medium",
      conditions: [{ fact: "hasCommunicationsPlan", operator: "is_false" }],
      evidenceFacts: ["hasCommunicationsPlan"],
      recommendationTemplate: "Elaborar el Plan de Comunicaciones del proyecto antes de iniciar la Ejecución.",
    },
    {
      id: "pb-plan-risk-register-missing",
      scope: "planificacion",
      title: "Registro de riesgos no inicializado",
      description: "No existe un registro de riesgos (RAID) inicializado para el proyecto.",
      severity: "high",
      conditions: [{ fact: "hasRiskRegister", operator: "is_false" }],
      evidenceFacts: ["hasRiskRegister"],
      recommendationTemplate: "Inicializar el registro de riesgos (RAID) antes de aprobar el paso a Ejecución.",
    },
    {
      id: "pb-exec-critical-risks-open",
      scope: "ejecucion",
      title: "Riesgos críticos abiertos",
      description: "Existen riesgos críticos sin mitigar durante la Ejecución.",
      severity: "critical",
      conditions: [{ fact: "openCriticalRisks", operator: "greater_than", value: 0 }],
      evidenceFacts: ["openCriticalRisks"],
      recommendationTemplate:
        "Escalar y asignar owner a los riesgos críticos abiertos; definir plan de mitigación inmediato.",
    },
    {
      id: "pb-exec-overdue-tasks",
      scope: "ejecucion",
      title: "Tareas vencidas",
      description: "Existen tareas vencidas sin resolución durante la Ejecución.",
      severity: "medium",
      conditions: [{ fact: "overdueTasks", operator: "greater_than", value: 0 }],
      evidenceFacts: ["overdueTasks"],
      recommendationTemplate: "Revisar tareas vencidas con los responsables y reprogramar o escalar según corresponda.",
    },
    {
      id: "pb-exec-schedule-variance",
      scope: "ejecucion",
      title: "Desviación de cronograma significativa",
      description: "El proyecto muestra una desviación de cronograma mayor al umbral aceptable.",
      severity: "high",
      conditions: [{ fact: "scheduleVarianceDays", operator: "greater_than", value: 5 }],
      evidenceFacts: ["scheduleVarianceDays"],
      recommendationTemplate:
        "Evaluar recuperación de cronograma (fast-tracking, crashing) o renegociar hitos con el sponsor.",
    },
    {
      id: "pb-exec-budget-variance",
      scope: "ejecucion",
      title: "Desviación de presupuesto significativa",
      description: "El proyecto muestra una desviación de presupuesto mayor al umbral aceptable.",
      severity: "high",
      conditions: [{ fact: "budgetVariancePercent", operator: "greater_than", value: 10 }],
      evidenceFacts: ["budgetVariancePercent"],
      recommendationTemplate: "Analizar la causa de la desviación presupuestaria y presentar opciones al sponsor.",
    },
    {
      id: "pb-monitor-open-issues",
      scope: "monitoreo_control",
      title: "Volumen de issues abiertos elevado",
      description: "El número de issues abiertos supera el umbral saludable definido por el playbook.",
      severity: "medium",
      conditions: [{ fact: "openIssues", operator: "greater_than_or_equal", value: 5 }],
      evidenceFacts: ["openIssues"],
      recommendationTemplate: "Priorizar la resolución de issues abiertos antes de que impacten el cronograma.",
    },
    {
      id: "pb-any-stale-status",
      scope: "any",
      title: "Actualización de estado desactualizada",
      description: "Han pasado más de dos semanas desde el último reporte de estado del proyecto.",
      severity: "medium",
      conditions: [{ fact: "daysSinceLastStatusUpdate", operator: "greater_than", value: 14 }],
      evidenceFacts: ["daysSinceLastStatusUpdate"],
      recommendationTemplate: "Generar una actualización de estado; se ha excedido la cadencia de reporte esperada.",
    },
    {
      id: "pb-close-signoff-missing",
      scope: "cierre",
      title: "Sign-off del cliente pendiente",
      description: "No se ha registrado el sign-off formal del cliente para el cierre del proyecto.",
      severity: "critical",
      conditions: [{ fact: "hasClientSignoff", operator: "is_false" }],
      evidenceFacts: ["hasClientSignoff"],
      recommendationTemplate: "Obtener el sign-off formal del cliente antes de declarar el cierre del proyecto.",
    },
    {
      id: "pb-close-invoice-missing",
      scope: "cierre",
      title: "Facturación final pendiente",
      description: "No se ha emitido la factura final del proyecto.",
      severity: "high",
      conditions: [{ fact: "hasFinalInvoiceIssued", operator: "is_false" }],
      evidenceFacts: ["hasFinalInvoiceIssued"],
      recommendationTemplate: "Emitir la factura final y conciliar el estado de facturación del proyecto.",
    },
    {
      id: "pb-close-checklist-not-started",
      scope: "cierre",
      title: "Checklist de cierre no iniciado",
      description: "No se ha iniciado el checklist formal de cierre del proyecto.",
      severity: "medium",
      conditions: [{ fact: "hasClosureChecklistStarted", operator: "is_false" }],
      evidenceFacts: ["hasClosureChecklistStarted"],
      recommendationTemplate: "Iniciar el checklist de cierre formal del proyecto.",
    },
  ],
};
