import type { CanonicalObjectKind } from "./contracts";

export const CONSUMER_CLASSIFICATIONS = ["CANONICAL", "ADAPTER", "BOUNDED_CONTEXT_MODEL", "READ_PROJECTION", "MIGRATION_SOURCE", "RETIREMENT_CANDIDATE", "UNKNOWN_REQUIRES_DECISION"] as const;
export type ConsumerClassification = (typeof CONSUMER_CLASSIFICATIONS)[number];
export type ConsumerOperation = "read" | "write" | "transition" | "project";
export type ConsumerMapEntry = Readonly<{
  path: string;
  symbol: string;
  objects: readonly CanonicalObjectKind[];
  operation: ConsumerOperation;
  classification: ConsumerClassification;
  owner: "operational-flow" | "decision-governance" | "recommended-actions" | "task-drafts" | "execution-tasks" | "agent-execution" | "operational-decision-outcome" | "frontend" | "database";
  compatibility: string;
  targetAdapter: string | null;
  retirementStatus: "retain" | "evaluate_after_g1" | "not_applicable";
  evidence: string;
}>;

export const OPERATIONAL_SPINE_CONSUMER_MAP: readonly ConsumerMapEntry[] = [
  { path: "src/lib/operational-flow/operational-flow-service.ts", symbol: "recordHumanDecision", objects: ["recommendation", "decision"], operation: "transition", classification: "CANONICAL", owner: "operational-flow", compatibility: "Preserve governed RPC and operational_decision_records ownership.", targetAdapter: null, retirementStatus: "not_applicable", evidence: "Calls record_operational_decision." },
  { path: "src/app/api/operational-flow/route.ts", symbol: "POST", objects: ["recommendation", "decision"], operation: "write", classification: "CANONICAL", owner: "operational-flow", compatibility: "Keep public operations separate and project-authorized.", targetAdapter: null, retirementStatus: "not_applicable", evidence: "Exposes run_chain and record_decision." },
  { path: "src/components/pmfreak/intelligence-inbox/project-intelligence-inbox.tsx", symbol: "ProjectIntelligenceInbox", objects: ["recommendation", "decision"], operation: "read", classification: "READ_PROJECTION", owner: "frontend", compatibility: "Consume canonical view without owning transitions.", targetAdapter: "operational-flow summary projection", retirementStatus: "retain", evidence: "Fetches /api/operational-flow." },
  { path: "src/lib/recommended-actions/decision-workflow.ts", symbol: "decideRecommendedAction", objects: ["recommendation"], operation: "transition", classification: "BOUNDED_CONTEXT_MODEL", owner: "recommended-actions", compatibility: "Retain legacy H3 status review; governed recommendations remain rejected by guard.", targetAdapter: "recommendation legacy reference", retirementStatus: "evaluate_after_g1", evidence: "Writes recommended_action_decisions and blocks governance_event_id." },
  { path: "src/lib/recommended-actions/materialize-recommended-actions.ts", symbol: "materializeRecommendedActions", objects: ["recommendation"], operation: "write", classification: "MIGRATION_SOURCE", owner: "recommended-actions", compatibility: "Preserve RAID-derived recommendations pending adapter proof.", targetAdapter: "recommendation source adapter", retirementStatus: "evaluate_after_g1", evidence: "Writes recommended_actions." },
  { path: "src/app/api/recommended-actions/route.ts", symbol: "GET", objects: ["recommendation"], operation: "read", classification: "READ_PROJECTION", owner: "recommended-actions", compatibility: "Keep legacy-only governance_event_id null filter.", targetAdapter: "recommendation legacy projection", retirementStatus: "evaluate_after_g1", evidence: "Reads legacy recommended_actions." },
  { path: "src/lib/decision-governance/service.ts", symbol: "createDecision", objects: ["decision"], operation: "write", classification: "BOUNDED_CONTEXT_MODEL", owner: "decision-governance", compatibility: "Retain evidence-linked project_decisions as governed bounded context.", targetAdapter: "decision legacy reference", retirementStatus: "evaluate_after_g1", evidence: "Writes project_decisions." },
  { path: "src/lib/decision-governance/service.ts", symbol: "buildDecisionLineage", objects: ["recommendation", "decision", "outcome"], operation: "project", classification: "ADAPTER", owner: "decision-governance", compatibility: "Preserve audit export; later accept canonical references.", targetAdapter: "canonical audit lineage adapter", retirementStatus: "retain", evidence: "Loads decision, recommendation, evidence, outcomes and events." },
  { path: "src/lib/audit-export/canonical-audit-export.ts", symbol: "buildCanonicalAuditExportPackage", objects: ["decision", "action", "task", "outcome"], operation: "project", classification: "READ_PROJECTION", owner: "operational-flow", compatibility: "Canonical P2-20 audit export; composes the verified lineage projection and audit reconstruction without owning state.", targetAdapter: null, retirementStatus: "not_applicable", evidence: "Redacts and versions getCompleteLineageProjection/reconstructAuditTrail output." },
  { path: "src/lib/audit-export/legacy-compatibility.ts", symbol: "exportLegacyDecisionAuditCompatibilityPackage", objects: ["decision", "outcome"], operation: "project", classification: "ADAPTER", owner: "decision-governance", compatibility: "Bounded legacy envelope over exportDecisionAuditPackage; marks canonical lineage unsupported instead of inventing it.", targetAdapter: "canonical audit lineage adapter", retirementStatus: "retain", evidence: "Wraps and redacts the legacy DecisionAuditPackage, preserving legacy IDs." },
  { path: "src/lib/decision-governance/state-machine.ts", symbol: "validateDecisionTransition", objects: ["decision"], operation: "transition", classification: "BOUNDED_CONTEXT_MODEL", owner: "decision-governance", compatibility: "Do not replace bounded project_decisions lifecycle.", targetAdapter: "decision state mapping", retirementStatus: "retain", evidence: "Validates project_decisions lifecycle." },
  { path: "src/lib/task-drafts/materialize-task-draft.ts", symbol: "materializeTaskDraftForRecommendedAction", objects: ["recommendation", "task"], operation: "transition", classification: "MIGRATION_SOURCE", owner: "task-drafts", compatibility: "Preserve H5 but never expose as canonical Action-to-Task.", targetAdapter: "legacy recommendation/task references", retirementStatus: "evaluate_after_g1", evidence: "Converts legacy recommendation directly to task draft." },
  { path: "src/app/api/task-drafts/from-recommended-action/route.ts", symbol: "POST", objects: ["recommendation", "task"], operation: "write", classification: "BOUNDED_CONTEXT_MODEL", owner: "task-drafts", compatibility: "Retain authenticated legacy materialization endpoint.", targetAdapter: "legacy H5 adapter", retirementStatus: "evaluate_after_g1", evidence: "Invokes task-draft materializer." },
  { path: "src/app/api/execution-tasks/convert/route.ts", symbol: "POST", objects: ["task"], operation: "write", classification: "ADAPTER", owner: "execution-tasks", compatibility: "Candidate internal Task SoR adapter for P2-07.", targetAdapter: "canonical Action-to-Task adapter", retirementStatus: "retain", evidence: "Converts approved draft to execution task." },
  { path: "src/app/api/execution-tasks/update/route.ts", symbol: "POST", objects: ["task"], operation: "transition", classification: "BOUNDED_CONTEXT_MODEL", owner: "execution-tasks", compatibility: "Preserve H6 lifecycle and authorization.", targetAdapter: "canonical task state mapping", retirementStatus: "retain", evidence: "Updates execution task lifecycle." },
  { path: "src/components/pmfreak/tasks/project-task-list.tsx", symbol: "ProjectTaskList", objects: ["task"], operation: "read", classification: "READ_PROJECTION", owner: "frontend", compatibility: "Continue reading internal Task SoR.", targetAdapter: "canonical task projection", retirementStatus: "retain", evidence: "Project page task consumer." },
  { path: "src/lib/operational-decision-outcome/outcome-registry.ts", symbol: "createDecisionOutcome", objects: ["decision", "outcome"], operation: "write", classification: "BOUNDED_CONTEXT_MODEL", owner: "operational-decision-outcome", compatibility: "Retain separate outcome engine; adapt after canonical Task chain exists.", targetAdapter: "canonical outcome reference", retirementStatus: "retain", evidence: "Creates operational_decision_outcomes." },
  { path: "src/lib/operational-decision-outcome/outcome-registry.ts", symbol: "recordOutcomeObservation", objects: ["outcome"], operation: "transition", classification: "ADAPTER", owner: "operational-decision-outcome", compatibility: "Candidate observation adapter; never infer from Task completion.", targetAdapter: "canonical outcome observation adapter", retirementStatus: "retain", evidence: "Creates separate observation." },
  { path: "src/app/api/agents/execution/outcomes/from-dispatch-attempt/route.ts", symbol: "POST", objects: ["action", "outcome"], operation: "write", classification: "BOUNDED_CONTEXT_MODEL", owner: "agent-execution", compatibility: "Keep agent dispatch outcome bounded and explicitly referenced.", targetAdapter: "agent outcome legacy reference", retirementStatus: "retain", evidence: "Creates agent result reconciliation outcome." },
  { path: "src/app/api/agents/execution/outcomes/[outcomeId]/review/route.ts", symbol: "POST", objects: ["outcome"], operation: "transition", classification: "BOUNDED_CONTEXT_MODEL", owner: "agent-execution", compatibility: "Retain human review in agent execution context.", targetAdapter: "agent observation reference", retirementStatus: "retain", evidence: "Reviews agent execution outcome." },
  { path: "supabase/migrations/20260611000000_operational_evidence_decision_loop.sql", symbol: "record_operational_decision", objects: ["recommendation", "decision"], operation: "transition", classification: "CANONICAL", owner: "database", compatibility: "Historical migration is immutable; extend only through forward migrations.", targetAdapter: null, retirementStatus: "not_applicable", evidence: "Transactional decision and evidence snapshot RPC." },
  { path: "supabase/migrations/20260605050000_recommended_actions_decision_workflow.sql", symbol: "recommended_action_decisions", objects: ["recommendation"], operation: "write", classification: "MIGRATION_SOURCE", owner: "database", compatibility: "Retain legacy audit history; do not reinterpret as canonical Decision.", targetAdapter: "recommendation review legacy reference", retirementStatus: "evaluate_after_g1", evidence: "Legacy H4 audit table." },
  { path: "src/lib/operational-decision/decision-registry.ts", symbol: "generateOperationalDecision", objects: ["decision"], operation: "write", classification: "BOUNDED_CONTEXT_MODEL", owner: "decision-governance", compatibility: "Retain analytical operational_decisions aggregate separately from commercial operational_decision_records.", targetAdapter: "decision legacy reference", retirementStatus: "retain", evidence: "Creates scored operational_decisions and options." },
  { path: "src/lib/operational-decision/decision-registry.ts", symbol: "getOperationalDecisionLineageForDecision", objects: ["decision", "outcome"], operation: "project", classification: "ADAPTER", owner: "decision-governance", compatibility: "Preserve analytical lineage as a bounded projection.", targetAdapter: "canonical lineage reference adapter", retirementStatus: "retain", evidence: "Builds operational decision lineage." },
  { path: "src/lib/operational-decision/decision-repository.ts", symbol: "dbUpdateDecisionStatus", objects: ["decision"], operation: "transition", classification: "BOUNDED_CONTEXT_MODEL", owner: "decision-governance", compatibility: "Keep analytical decision lifecycle local to its aggregate.", targetAdapter: "decision state mapping", retirementStatus: "retain", evidence: "Updates operational_decisions status." },
  { path: "src/lib/execution-tasks/create-execution-task.ts", symbol: "createExecutionTaskDirect", objects: ["task"], operation: "write", classification: "BOUNDED_CONTEXT_MODEL", owner: "execution-tasks", compatibility: "Preserve direct human task creation as ordinary PM business work.", targetAdapter: "canonical task reference", retirementStatus: "retain", evidence: "Creates internal execution_tasks with project authorization." },
  { path: "src/lib/execution-tasks/convert-task-draft.ts", symbol: "convertTaskDraftToExecutionTask", objects: ["task"], operation: "transition", classification: "ADAPTER", owner: "execution-tasks", compatibility: "Retain H5/H6 conversion and later require canonical Action for governed path.", targetAdapter: "canonical Action-to-Task adapter", retirementStatus: "retain", evidence: "Converts approved task_draft to execution_task." },
  { path: "src/app/api/execution-tasks/route.ts", symbol: "POST", objects: ["task"], operation: "write", classification: "BOUNDED_CONTEXT_MODEL", owner: "execution-tasks", compatibility: "Keep server-authorized direct PM task command distinct from governed dispatch.", targetAdapter: "canonical task command", retirementStatus: "retain", evidence: "Calls createExecutionTaskDirect." },
  { path: "src/components/pmfreak/tasks/quick-add-task-modal.tsx", symbol: "QuickAddTaskModal", objects: ["task"], operation: "write", classification: "READ_PROJECTION", owner: "frontend", compatibility: "Continue ordinary direct PM task UX; never imply it came from an Action.", targetAdapter: "canonical task command UI", retirementStatus: "retain", evidence: "Posts a direct internal task." },
  { path: "src/app/api/agents/audit/decisions/route.ts", symbol: "POST", objects: ["decision"], operation: "write", classification: "BOUNDED_CONTEXT_MODEL", owner: "agent-execution", compatibility: "Retain agent audit decision as governance evidence, not PM business Decision.", targetAdapter: "agent decision legacy reference", retirementStatus: "retain", evidence: "Creates agent observability audit decision." },
  { path: "src/lib/decision-effectiveness/effectiveness-service.ts", symbol: "buildDecisionEffectivenessLineage", objects: ["decision", "outcome"], operation: "project", classification: "READ_PROJECTION", owner: "decision-governance", compatibility: "Retain effectiveness analysis as downstream projection, never causal truth.", targetAdapter: "canonical decision/outcome references", retirementStatus: "retain", evidence: "Projects project_decisions and outcomes into effectiveness lineage." },
  { path: "src/lib/operational-decision-outcome/lineage-engine.ts", symbol: "getDecisionOutcomeLineage", objects: ["decision", "outcome"], operation: "project", classification: "ADAPTER", owner: "operational-decision-outcome", compatibility: "Reuse lineage engine behind canonical references after P2-09.", targetAdapter: "canonical outcome lineage adapter", retirementStatus: "retain", evidence: "Joins operational decision outcome observations/effects/learning." },
] as const;

export type ConsumerMapValidationIssue = Readonly<{ index: number; field: string; message: string }>;
export function validateConsumerMap(entries: readonly ConsumerMapEntry[]): readonly ConsumerMapValidationIssue[] {
  const issues: ConsumerMapValidationIssue[] = [];
  const identities = new Set<string>();
  entries.forEach((entry, index) => {
    for (const field of ["path", "symbol", "compatibility", "evidence"] as const) {
      if (!entry[field].trim()) issues.push({ index, field, message: "must be non-empty" });
    }
    if (entry.objects.length === 0) issues.push({ index, field: "objects", message: "must contain a canonical object" });
    const identity = `${entry.path}#${entry.symbol}:${entry.operation}`;
    if (identities.has(identity)) issues.push({ index, field: "identity", message: "must be unique" });
    identities.add(identity);
    if (entry.classification === "UNKNOWN_REQUIRES_DECISION" && entry.retirementStatus !== "retain") {
      issues.push({ index, field: "retirementStatus", message: "unknown consumers must be retained" });
    }
  });
  return issues;
}

export function summarizeConsumerMap(entries: readonly ConsumerMapEntry[] = OPERATIONAL_SPINE_CONSUMER_MAP) {
  const classifications = Object.fromEntries(CONSUMER_CLASSIFICATIONS.map((value) => [value, 0])) as Record<ConsumerClassification, number>;
  for (const entry of entries) classifications[entry.classification] += 1;
  return { total: entries.length, classifications, unresolved: classifications.UNKNOWN_REQUIRES_DECISION } as const;
}
