import { createHash, randomUUID } from "node:crypto";

import type { SupabaseClient } from "@supabase/supabase-js";

import type {
  AssumptionDiscoveryItem,
  DependencyDiscoveryItem,
  ProjectDiscoveryModel,
  RiskDiscoveryItem,
  UnknownDiscoveryItem,
} from "@/lib/project-discovery/discovery-agent";
import { canonicalRaidFingerprint } from "@/lib/raid";
import type { RaidCategory, RaidItem } from "@/lib/raid";

type DiscoveryRaidFinding = {
  category: RaidCategory;
  text: string;
  confidence: number;
  evidenceId: string;
  sourceFileName: string;
};

type ExistingDiscoveryRaidRow = {
  id: string;
  confidence_score: number;
  auto_generated: boolean;
  occurrence_count: number | null;
};

type MaterializationCandidate = Omit<RaidItem, "id"> & {
  id: string;
  evidenceId: string;
  sourceFileName: string;
};

export type DiscoveryRaidMaterializationResult = {
  created: number;
  updated: number;
  skipped: number;
};

const clampConfidence = (value: number) => Math.max(0, Math.min(100, Math.round(value)));

const cleanTitle = (value: string) =>
  value
    .replace(/^[-*\s]+/, "")
    .replace(/\s+/g, " ")
    .trim()
    .slice(0, 96)
    .replace(/[.;:,\s]+$/, "");

const contentHash = (value: string) => createHash("sha256").update(value, "utf8").digest("hex");
const discoveryRaidFingerprint = (category: RaidCategory, text: string) =>
  `project_discovery:${category}:${contentHash(canonicalRaidFingerprint(category, text))}`;

const discoverySourceDocumentMarker = (input: {
  projectId: string;
  workspaceId: string;
  discoveryId: string;
  discoveryVersion: number;
  discoveryPayloadHash: string;
}) =>
  `project_discovery_raid_source:${input.projectId}:${input.workspaceId}:${input.discoveryId}:v${input.discoveryVersion}:${input.discoveryPayloadHash}`;

function riskFinding(item: RiskDiscoveryItem): DiscoveryRaidFinding {
  return {
    category: "risk",
    text: item.risk,
    confidence: item.confidence,
    evidenceId: item.evidence_source.evidence_id,
    sourceFileName: item.evidence_source.source_file_name,
  };
}

function dependencyFinding(item: DependencyDiscoveryItem): DiscoveryRaidFinding {
  return {
    category: "dependency",
    text: item.dependency,
    confidence: item.confidence,
    evidenceId: item.evidence_source.evidence_id,
    sourceFileName: item.evidence_source.source_file_name,
  };
}

function assumptionFinding(item: AssumptionDiscoveryItem): DiscoveryRaidFinding {
  return {
    category: "assumption",
    text: item.assumption,
    confidence: item.confidence,
    evidenceId: item.evidence_source.evidence_id,
    sourceFileName: item.evidence_source.source_file_name,
  };
}

function unknownFinding(item: UnknownDiscoveryItem): DiscoveryRaidFinding {
  return {
    category: "issue",
    text: item.unknown,
    confidence: item.confidence,
    evidenceId: item.evidence_source.evidence_id,
    sourceFileName: item.evidence_source.source_file_name,
  };
}

export function projectDiscoveryRaidFindings(discovery: ProjectDiscoveryModel): DiscoveryRaidFinding[] {
  return [
    ...discovery.risks.map(riskFinding),
    ...discovery.dependencies.map(dependencyFinding),
    ...discovery.assumptions.map(assumptionFinding),
    ...discovery.unknowns.map(unknownFinding),
  ].filter((finding) => finding.text.trim().length > 0);
}

function buildCandidates(input: {
  discovery: ProjectDiscoveryModel;
  workspaceId: string;
  projectId: string;
  sourceDocumentId: string;
  detectedAt: string;
}): MaterializationCandidate[] {
  const deduped = new Map<string, DiscoveryRaidFinding>();

  for (const finding of projectDiscoveryRaidFindings(input.discovery)) {
    const fingerprint = discoveryRaidFingerprint(finding.category, finding.text);
    const existing = deduped.get(`${finding.category}:${fingerprint}`);
    if (!existing || clampConfidence(finding.confidence) > clampConfidence(existing.confidence)) {
      deduped.set(`${finding.category}:${fingerprint}`, finding);
    }
  }

  return Array.from(deduped.values()).map((finding) => {
    const fingerprint = discoveryRaidFingerprint(finding.category, finding.text);
    return {
      id: randomUUID(),
      workspaceId: input.workspaceId,
      projectId: input.projectId,
      sourceDocumentId: input.sourceDocumentId,
      sourceSignalId: null,
      category: finding.category,
      title: cleanTitle(finding.text),
      description: finding.text,
      status: "open",
      confidenceScore: clampConfidence(finding.confidence),
      detectedAt: input.detectedAt,
      lastDetectedAt: input.detectedAt,
      detectedBy: null,
      owner: null,
      dueDate: null,
      autoGenerated: true,
      fingerprint,
      occurrenceCount: 1,
      evidenceId: finding.evidenceId,
      sourceFileName: finding.sourceFileName,
    };
  });
}

function toRaidInsertRow(item: MaterializationCandidate) {
  return {
    id: item.id,
    workspace_id: item.workspaceId,
    project_id: item.projectId,
    source_document_id: item.sourceDocumentId,
    source_signal_id: item.sourceSignalId,
    category: item.category,
    title: item.title,
    description: item.description,
    status: item.status,
    confidence_score: item.confidenceScore,
    detected_at: item.detectedAt,
    last_detected_at: item.lastDetectedAt,
    detected_by: item.detectedBy,
    owner: item.owner,
    due_date: item.dueDate,
    auto_generated: item.autoGenerated,
    fingerprint: item.fingerprint,
    occurrence_count: item.occurrenceCount,
  };
}

async function findOrCreateDiscoverySourceDocument(input: {
  supabase: SupabaseClient;
  discoveryId: string;
  discoveryVersion: number;
  workspaceId: string;
  projectId: string;
  discovery: ProjectDiscoveryModel;
}): Promise<{ id: string; created: boolean }> {
  const discoveryPayloadHash = contentHash(JSON.stringify(input.discovery));
  const marker = discoverySourceDocumentMarker({
    projectId: input.projectId,
    workspaceId: input.workspaceId,
    discoveryId: input.discoveryId,
    discoveryVersion: input.discoveryVersion,
    discoveryPayloadHash,
  });

  const { data: existing, error: selectError } = await input.supabase
    .from("vault_documents")
    .select("id")
    .eq("workspace_id", input.workspaceId)
    .eq("project_id", input.projectId)
    .eq("source_type", "project_update")
    .eq("classification", "operational")
    .eq("normalized_content", marker)
    .maybeSingle<{ id: string }>();

  if (selectError) throw new Error(`Unable to query Project Discovery RAID source document: ${selectError.message}`);
  if (existing) return { id: existing.id, created: false };

  const { data, error } = await input.supabase
    .from("vault_documents")
    .insert({
      workspace_id: input.workspaceId,
      project_id: input.projectId,
      title: `Project Discovery RAID Materialization v${input.discoveryVersion}`,
      source_type: "project_update",
      classification: "operational",
      raw_content: JSON.stringify({ discovery_id: input.discoveryId, ...input.discovery }),
      normalized_content: marker,
      ingestion_status: "completed",
    })
    .select("id")
    .single<{ id: string }>();

  if (error) throw new Error(`Unable to create Project Discovery RAID source document: ${error.message}`);
  return { id: data.id, created: true };
}

export async function materializeProjectDiscoveryRaidItems(input: {
  discovery: ProjectDiscoveryModel;
  discoveryId: string;
  discoveryVersion: number;
  workspaceId: string;
  projectId: string;
  supabase: SupabaseClient;
  requestId?: string;
}): Promise<DiscoveryRaidMaterializationResult> {
  const startedAt = Date.now();
  const findings = projectDiscoveryRaidFindings(input.discovery);

  console.info("raid.materialization.started", {
    requestId: input.requestId,
    projectId: input.projectId,
    workspaceId: input.workspaceId,
    discoveryId: input.discoveryId,
    discoveryVersion: input.discoveryVersion,
    findingsCount: findings.length,
  });

  try {
    if (findings.length === 0) {
      const emptyResult = { created: 0, updated: 0, skipped: 0 };
      console.info("raid.materialization.completed", {
        requestId: input.requestId,
        projectId: input.projectId,
        discoveryId: input.discoveryId,
        sourceDocumentCreated: false,
        sourceDocumentReused: false,
        ...emptyResult,
        durationMs: Date.now() - startedAt,
      });
      return emptyResult;
    }

    const sourceDocumentResult = await findOrCreateDiscoverySourceDocument(input);
    console.info(
      sourceDocumentResult.created
        ? "raid.materialization.source_document.created"
        : "raid.materialization.source_document.reused",
      { projectId: input.projectId, discoveryId: input.discoveryId, sourceDocumentId: sourceDocumentResult.id },
    );

    const detectedAt = new Date().toISOString();
    const candidates = buildCandidates({
      discovery: input.discovery,
      workspaceId: input.workspaceId,
      projectId: input.projectId,
      sourceDocumentId: sourceDocumentResult.id,
      detectedAt,
    });

    let created = 0;
    let updated = 0;

    for (const item of candidates) {
      const { data: existing, error: selectError } = await input.supabase
        .from("raid_items")
        .select("id, confidence_score, auto_generated, occurrence_count")
        .eq("workspace_id", item.workspaceId)
        .eq("project_id", item.projectId)
        .eq("category", item.category)
        .eq("fingerprint", item.fingerprint)
        .limit(1)
        .maybeSingle<ExistingDiscoveryRaidRow>();

      if (selectError) throw new Error(`Unable to check existing discovery RAID item: ${selectError.message}`);

      if (existing) {
        const confidenceScore = clampConfidence(Math.max(Number(existing.confidence_score ?? 0), item.confidenceScore));
        const existingOccurrenceCount =
          typeof existing.occurrence_count === "number" && existing.occurrence_count >= 1
            ? existing.occurrence_count
            : 1;
        const { error: updateError } = await input.supabase
          .from("raid_items")
          .update({
            last_detected_at: item.lastDetectedAt,
            confidence_score: confidenceScore,
            occurrence_count: existingOccurrenceCount + 1,
          })
          .eq("id", existing.id);
        if (updateError) throw new Error(`Unable to update existing discovery RAID item: ${updateError.message}`);
        updated += 1;
        continue;
      }

      const { error: insertError } = await input.supabase.from("raid_items").insert(toRaidInsertRow(item));
      if (insertError) throw new Error(`Unable to insert discovery RAID item: ${insertError.message}`);
      created += 1;
    }

    const result = { created, updated, skipped: findings.length - candidates.length };
    console.info("raid.materialization.completed", {
      requestId: input.requestId,
      projectId: input.projectId,
      discoveryId: input.discoveryId,
      sourceDocumentCreated: sourceDocumentResult.created,
      sourceDocumentReused: !sourceDocumentResult.created,
      ...result,
      durationMs: Date.now() - startedAt,
    });
    return result;
  } catch (error) {
    console.error("raid.materialization.failed", {
      requestId: input.requestId,
      projectId: input.projectId,
      workspaceId: input.workspaceId,
      discoveryId: input.discoveryId,
      durationMs: Date.now() - startedAt,
      error: error instanceof Error ? error.message : "unknown",
    });
    throw error;
  }
}
