import type { SupabaseClient } from "@supabase/supabase-js";
import { buildRaidOverview, type RaidItem } from "@/lib/raid";
import { generateOperationalGovernanceBrief } from "./operational-governance-brief-engine";
import { persistOperationalGovernanceBrief, type PersistOperationalGovernanceBriefResult } from "./operational-governance-brief-store";
import type { OperationalGovernanceBrief } from "./operational-governance-brief-types";

export type GenerateAndPersistBriefInput = {
  workspaceId: string;
  projectId: string;
  projectOnboardingPayload: Record<string, unknown> | null;
  createdBy: string;
  supabase: SupabaseClient;
};

export type GenerateAndPersistBriefResult =
  | { ok: true; brief: OperationalGovernanceBrief }
  | { ok: false; brief: OperationalGovernanceBrief; error: string };

export async function generateAndPersistOperationalGovernanceBrief({
  workspaceId,
  projectId,
  projectOnboardingPayload,
  createdBy,
  supabase,
}: GenerateAndPersistBriefInput): Promise<GenerateAndPersistBriefResult> {
  const [{ data: governanceRow }, { data: runtimeRow }, { data: raidRows }] = await Promise.all([
    supabase
      .from("workspace_governance")
      .select("governance_jsonb")
      .eq("workspace_id", workspaceId)
      .eq("status", "active")
      .order("updated_at", { ascending: false })
      .limit(1)
      .maybeSingle<{ governance_jsonb: Record<string, unknown> }>(),
    supabase
      .from("workspace_runtime_state")
      .select("awakening_state, imprint_state, validation_state, flags")
      .eq("workspace_id", workspaceId)
      .eq("user_id", createdBy)
      .limit(1)
      .maybeSingle<Record<string, unknown>>(),
    supabase
      .from("raid_items")
      .select("id, workspace_id, project_id, source_document_id, source_signal_id, category, title, description, status, confidence_score, detected_at, detected_by, owner, due_date, auto_generated, fingerprint, occurrence_count, last_detected_at")
      .eq("workspace_id", workspaceId)
      .eq("project_id", projectId)
      .in("status", ["open", "monitoring"])
      .order("confidence_score", { ascending: false })
      .limit(25),
  ]);

  const detectedRaidOverview = buildRaidOverview((raidRows ?? []).map((row: Record<string, unknown>) => ({
    id: String(row.id),
    workspaceId: String(row.workspace_id),
    projectId: typeof row.project_id === "string" ? row.project_id : null,
    sourceDocumentId: String(row.source_document_id),
    sourceSignalId: typeof row.source_signal_id === "string" ? row.source_signal_id : null,
    category: row.category as RaidItem["category"],
    title: String(row.title),
    description: String(row.description),
    status: row.status as RaidItem["status"],
    confidenceScore: Number(row.confidence_score ?? 0),
    detectedAt: String(row.detected_at),
    detectedBy: typeof row.detected_by === "string" ? row.detected_by : null,
    owner: typeof row.owner === "string" ? row.owner : null,
    dueDate: typeof row.due_date === "string" ? row.due_date : null,
    autoGenerated: row.auto_generated !== false,
    fingerprint: String(row.fingerprint),
    occurrenceCount: Number(row.occurrence_count ?? 1),
    lastDetectedAt: String(row.last_detected_at ?? row.detected_at),
  })));

  const brief = generateOperationalGovernanceBrief({
    workspaceId,
    projectId,
    pmoGovernance: governanceRow?.governance_jsonb ?? null,
    projectOnboardingPayload,
    workspaceRuntimeState: runtimeRow ?? null,
    detectedRaidOverview: {
      topRisks: detectedRaidOverview.topRisks,
      topIssues: detectedRaidOverview.topIssues,
      keyDependencies: detectedRaidOverview.keyDependencies,
      keyAssumptions: detectedRaidOverview.keyAssumptions,
      snapshot: detectedRaidOverview.snapshot,
      healthScore: detectedRaidOverview.health.healthScore,
    },
  });

  const persisted: PersistOperationalGovernanceBriefResult = await persistOperationalGovernanceBrief({
    brief,
    createdBy,
    supabase,
  });

  if (!persisted.ok) return { ok: false, brief, error: persisted.error };
  return { ok: true, brief };
}
