import type { RegisterAgentToolInput } from "./agent-tool-types";

// Default PMFreak agent tools seeded into every workspace.
// All compatible_agent_types align with the ai_agents.agent_type check constraint
// plus the PMFreak-specific agent role identifiers.

export const DEFAULT_AGENT_TOOLS: Omit<RegisterAgentToolInput, "workspaceId">[] = [
  {
    toolKey: "read_project_summary",
    displayName: "Read Project Summary",
    description: "Retrieve the current summary and status of a project.",
    category: "project_read",
    riskLevel: "low",
    executionMode: "read_only",
    createsEvidence: false,
    mutatesState: false,
    requiresHumanApproval: false,
    compatibleAgentTypes: [
      "copilot","analyzer","governance_assistant",
      "project_assistant","pmo_analyst","executive_reporter",
    ],
  },
  {
    toolKey: "read_project_risks",
    displayName: "Read Project Risks",
    description: "Retrieve active risks registered against a project.",
    category: "project_read",
    riskLevel: "low",
    executionMode: "read_only",
    createsEvidence: false,
    mutatesState: false,
    requiresHumanApproval: false,
    compatibleAgentTypes: [
      "copilot","analyzer","governance_assistant",
      "project_assistant","pmo_analyst","governance_agent",
    ],
  },
  {
    toolKey: "read_project_timeline",
    displayName: "Read Project Timeline",
    description: "Retrieve the timeline, milestones, and delivery schedule for a project.",
    category: "project_read",
    riskLevel: "low",
    executionMode: "read_only",
    createsEvidence: false,
    mutatesState: false,
    requiresHumanApproval: false,
    compatibleAgentTypes: [
      "copilot","analyzer","governance_assistant",
      "project_assistant","pmo_analyst",
    ],
  },
  {
    toolKey: "read_pm_capacity_snapshot",
    displayName: "Read PM Capacity Snapshot",
    description: "Read the latest PM capacity and load snapshot for a given PM.",
    category: "pm_read",
    riskLevel: "low",
    executionMode: "read_only",
    createsEvidence: false,
    mutatesState: false,
    requiresHumanApproval: false,
    compatibleAgentTypes: [
      "copilot","analyzer","governance_assistant",
      "pmo_analyst","governance_agent",
    ],
  },
  {
    toolKey: "classify_project_status",
    displayName: "Classify Project Status",
    description: "Analyse project signals and classify current delivery status.",
    category: "analysis",
    riskLevel: "low",
    executionMode: "read_only",
    createsEvidence: true,
    mutatesState: false,
    requiresHumanApproval: false,
    compatibleAgentTypes: [
      "analyzer","governance_assistant",
      "project_assistant","pmo_analyst","governance_agent",
    ],
  },
  {
    toolKey: "draft_project_update",
    displayName: "Draft Project Update",
    description: "Generate a draft project status update for PM review before sending.",
    category: "drafting",
    riskLevel: "medium",
    executionMode: "draft_only",
    createsEvidence: true,
    mutatesState: false,
    requiresHumanApproval: false,
    compatibleAgentTypes: [
      "copilot","analyzer",
      "project_assistant","pmo_analyst",
    ],
  },
  {
    toolKey: "draft_client_email",
    displayName: "Draft Client Email",
    description: "Compose a draft email to a project client. Requires human approval before sending.",
    category: "communication",
    riskLevel: "medium",
    executionMode: "draft_only",
    createsEvidence: true,
    mutatesState: false,
    requiresHumanApproval: true,
    compatibleAgentTypes: [
      "copilot","project_assistant",
    ],
  },
  {
    toolKey: "create_task_draft",
    displayName: "Create Task Draft",
    description: "Generate a draft task for PM review. Does not create the task in the system.",
    category: "task_generation",
    riskLevel: "medium",
    executionMode: "draft_only",
    createsEvidence: true,
    mutatesState: false,
    requiresHumanApproval: false,
    compatibleAgentTypes: [
      "copilot","workflow_runner","project_assistant","pmo_analyst",
    ],
  },
  {
    toolKey: "suggest_intervention",
    displayName: "Suggest Intervention",
    description: "Propose a governance intervention for a project at risk.",
    category: "recommendation",
    riskLevel: "medium",
    executionMode: "draft_only",
    createsEvidence: true,
    mutatesState: false,
    requiresHumanApproval: false,
    compatibleAgentTypes: [
      "analyzer","governance_assistant",
      "pmo_analyst","intervention_agent","governance_agent",
    ],
  },
  {
    toolKey: "generate_executive_summary",
    displayName: "Generate Executive Summary",
    description: "Generate an executive-level portfolio or project summary report.",
    category: "reporting",
    riskLevel: "medium",
    executionMode: "draft_only",
    createsEvidence: true,
    mutatesState: false,
    requiresHumanApproval: false,
    compatibleAgentTypes: [
      "analyzer","executive_reporter","pmo_analyst",
    ],
  },
  {
    toolKey: "recommend_next_action",
    displayName: "Recommend Next Action",
    description: "Recommend the most impactful next action for a PM or project.",
    category: "recommendation",
    riskLevel: "medium",
    executionMode: "draft_only",
    createsEvidence: true,
    mutatesState: false,
    requiresHumanApproval: false,
    compatibleAgentTypes: [
      "copilot","analyzer","governance_assistant",
      "project_assistant","pmo_analyst","intervention_agent",
    ],
  },
  {
    toolKey: "analyze_meeting_notes",
    displayName: "Analyze Meeting Notes",
    description: "Extract actions, risks, and decisions from meeting notes.",
    category: "analysis",
    riskLevel: "low",
    executionMode: "read_only",
    createsEvidence: true,
    mutatesState: false,
    requiresHumanApproval: false,
    compatibleAgentTypes: [
      "copilot","analyzer","project_assistant",
    ],
  },
];
