import { createSupabaseServerClient } from "@/lib/supabase/server";
import { buildRaidOverview } from "@/lib/raid";
import type { RaidItem } from "@/lib/raid";
import { computeScheduleHealth } from "@/lib/schedule/health";
import { computeProjectForecast } from "@/lib/critical-path/forecast";
import {
  RAID_ITEM_SELECTABLE_COLUMNS,
  EXECUTION_TASK_SELECTABLE_COLUMNS,
  PROJECT_MILESTONE_SELECTABLE_COLUMNS,
  EXECUTION_TASK_DEPENDENCY_SELECTABLE_COLUMNS,
  type ExecutionTaskRow,
  type ProjectMilestoneRow,
  type ExecutionTaskDependencyRow,
} from "@/lib/db/database-contract";
import type { HealthBand } from "@/platform/components/types";

export type ProjectHealth = {
  projectId: string;
  overallScore: number;
  band: HealthBand;
  raid: ReturnType<typeof buildRaidOverview>["health"];
  raidOverview: ReturnType<typeof buildRaidOverview>;
  schedule: ReturnType<typeof computeScheduleHealth>;
  forecast: ReturnType<typeof computeProjectForecast>;
  decisionsNeeded: number;
};

type RaidRow = {
  category: RaidItem["category"];
  status: RaidItem["status"];
  confidence_score: number;
};

/**
 * Composes real, existing RAID/schedule/critical-path computation into a
 * single Project Health projection — GetProjectHealth per 06-query-catalog.md.
 * No existing aggregator does this today (per PR9 reconnaissance); this is
 * the one new pure-composition function the health adapter needed, not a
 * new domain concept — every input is already a real, working service.
 *
 * Band thresholds are illustrative (08-design-system.md §6 leaves exact
 * thresholds open, same as ConfidenceScore's bands).
 */
export function composeProjectHealth(input: {
  projectId: string;
  raidRows: RaidRow[];
  tasks: ExecutionTaskRow[];
  milestones: ProjectMilestoneRow[];
  dependencies: ExecutionTaskDependencyRow[];
  pendingDecisionsCount: number;
  now?: Date;
}): ProjectHealth {
  const raidOverview = buildRaidOverview(
    input.raidRows.map((row, index) => ({
      id: String(index),
      workspaceId: "",
      projectId: input.projectId,
      sourceDocumentId: "",
      sourceSignalId: null,
      category: row.category,
      title: "",
      description: "",
      status: row.status,
      confidenceScore: row.confidence_score,
      detectedAt: "",
      lastDetectedAt: "",
      detectedBy: null,
      owner: null,
      dueDate: null,
      autoGenerated: true,
      fingerprint: "",
      occurrenceCount: 1,
    })),
  );

  const schedule = computeScheduleHealth({ tasks: input.tasks, milestones: input.milestones, dependencies: input.dependencies, now: input.now });
  const forecast = computeProjectForecast(input.tasks);

  const overallScore = Math.round((raidOverview.health.healthScore + schedule.scheduleConfidence) / 2);
  const band: HealthBand = overallScore >= 75 ? "strong" : overallScore >= 50 ? "watch" : "at-risk";

  return {
    projectId: input.projectId,
    overallScore,
    band,
    raid: raidOverview.health,
    raidOverview,
    schedule,
    forecast,
    decisionsNeeded: input.pendingDecisionsCount,
  };
}

export async function getProjectHealth(projectId: string, pendingDecisionsCount = 0): Promise<ProjectHealth> {
  const supabase = await createSupabaseServerClient();

  const [raidResult, taskResult, milestoneResult, dependencyResult] = await Promise.all([
    supabase.from("raid_items").select(RAID_ITEM_SELECTABLE_COLUMNS.join(",")).eq("project_id", projectId),
    supabase.from("execution_tasks").select(EXECUTION_TASK_SELECTABLE_COLUMNS.join(",")).eq("project_id", projectId),
    supabase.from("project_milestones").select(PROJECT_MILESTONE_SELECTABLE_COLUMNS.join(",")).eq("project_id", projectId),
    supabase.from("execution_task_dependencies").select(EXECUTION_TASK_DEPENDENCY_SELECTABLE_COLUMNS.join(",")).eq("project_id", projectId),
  ]);

  return composeProjectHealth({
    projectId,
    raidRows: (raidResult.data ?? []) as unknown as RaidRow[],
    tasks: (taskResult.data ?? []) as unknown as ExecutionTaskRow[],
    milestones: (milestoneResult.data ?? []) as unknown as ProjectMilestoneRow[],
    dependencies: (dependencyResult.data ?? []) as unknown as ExecutionTaskDependencyRow[],
    pendingDecisionsCount,
  });
}
