import type { SupabaseClient } from "@supabase/supabase-js";
import type { RaidItem } from "./types";

export type RaidPersistenceResult =
  | { ok: true; created: RaidItem[]; updated: RaidItem[] }
  | { ok: false; error: string };

type ExistingRaidRow = {
  id: string;
  occurrence_count: number;
  confidence_score: number;
  status: RaidItem["status"];
};

function toRaidInsertRow(item: RaidItem) {
  return {
    id: item.id,
    workspace_id: item.workspaceId,
    project_id: item.projectId,
    source_document_id: item.sourceDocumentId,
    source_signal_id: item.sourceSignalId,
    category: item.category,
    title: item.title,
    description: item.description,
    status: item.status,
    confidence_score: item.confidenceScore,
    detected_at: item.detectedAt,
    last_detected_at: item.lastDetectedAt,
    detected_by: item.detectedBy,
    owner: item.owner,
    due_date: item.dueDate,
    auto_generated: item.autoGenerated,
    fingerprint: item.fingerprint,
    occurrence_count: item.occurrenceCount,
  };
}

function reinforcedConfidence(existing: ExistingRaidRow, item: RaidItem, occurrenceCount: number): number {
  const strongestSignal = Math.max(Number(existing.confidence_score ?? 0), item.confidenceScore);
  return Math.min(100, strongestSignal + Math.min(12, occurrenceCount * 2));
}

export async function persistRaidItems({
  items,
  supabase,
}: {
  items: RaidItem[];
  supabase: SupabaseClient;
}): Promise<RaidPersistenceResult> {
  const created: RaidItem[] = [];
  const updated: RaidItem[] = [];

  for (const item of items) {
    const query = supabase
      .from("raid_items")
      .select("id, occurrence_count, confidence_score, status")
      .eq("workspace_id", item.workspaceId)
      .eq("category", item.category)
      .eq("fingerprint", item.fingerprint)
      .limit(1);
    const scopedQuery = item.projectId ? query.eq("project_id", item.projectId) : query.is("project_id", null);
    const { data: existing, error: selectError } = await scopedQuery.maybeSingle<ExistingRaidRow>();
    if (selectError) return { ok: false, error: selectError.message };

    if (existing) {
      const occurrenceCount = Number(existing.occurrence_count ?? 1) + 1;
      const confidenceScore = reinforcedConfidence(existing, item, occurrenceCount);
      const status = existing.status === "open" || existing.status === "monitoring" ? existing.status : item.status;
      const { error: updateError } = await supabase
        .from("raid_items")
        .update({
          occurrence_count: occurrenceCount,
          confidence_score: confidenceScore,
          last_detected_at: item.detectedAt,
          source_document_id: item.sourceDocumentId,
          source_signal_id: item.sourceSignalId,
          status,
          owner: item.owner,
          due_date: item.dueDate,
        })
        .eq("id", existing.id);
      if (updateError) return { ok: false, error: updateError.message };
      updated.push({ ...item, id: existing.id, occurrenceCount, confidenceScore, status, lastDetectedAt: item.detectedAt });
      continue;
    }

    const { error: insertError } = await supabase.from("raid_items").insert(toRaidInsertRow(item));
    if (insertError) return { ok: false, error: insertError.message };
    created.push(item);
  }

  return { ok: true, created, updated };
}
