export type RaidCategory = "risk" | "assumption" | "issue" | "dependency";

export type RaidStatus = "open" | "monitoring" | "mitigated" | "closed";

export type RaidItem = {
  id: string;
  workspaceId: string;
  projectId: string | null;
  sourceDocumentId: string;
  sourceSignalId: string | null;
  category: RaidCategory;
  title: string;
  description: string;
  status: RaidStatus;
  confidenceScore: number;
  detectedAt: string;
  lastDetectedAt: string;
  detectedBy: string | null;
  owner: string | null;
  dueDate: string | null;
  autoGenerated: boolean;
  fingerprint: string;
  occurrenceCount: number;
};

export type ProjectRaidHealth = {
  riskCount: number;
  issueCount: number;
  dependencyCount: number;
  assumptionCount: number;
  criticalRiskCount: number;
  healthScore: number;
};

export type RaidSnapshot = {
  risks: number;
  issues: number;
  dependencies: number;
  assumptions: number;
};

export type RaidOverview = {
  topRisks: string[];
  topIssues: string[];
  keyDependencies: string[];
  keyAssumptions: string[];
  health: ProjectRaidHealth;
  snapshot: RaidSnapshot;
};
